
PORTUGUESE_MAPPING = {
    "nif_issuer": "NIF do Emissor",
    "nif_acquirer": "NIF do Adquirente",
    "country": "País do adquirente",
    "doc_type": "Tipo de documento",
    "doc_state": "Estado do documento",
    "doc_date": "Data do documento",
    "unique_id": "Identificador único do documento",
    "atcud": "ATCUD",
    "fiscal_space": "Espaço fiscal 1",
    "base_taxable_exempt_iva": "Base tributável isenta de IVA",
    "base_taxable_reduced_iva": "Base tributável a taxa reduzida de IVA",
    "total_reduced_iva": "Total do IVA a taxa reduzida",
    "base_taxable_intermediate_iva": "Base tributável a taxa intermédia de IVA",
    "total_intermediate_iva": "Total do IVA a taxa intermédia",
    "base_taxable_normal_iva": "Base tributável a taxa normal de IVA",
    "total_normal_iva": "Total do IVA a taxa normal",
    "fiscal_space_2": "Espaço fiscal 2",
    "base_taxable_exempt_iva_2": "Base tributável isenta de IVA",
    "base_taxable_reduced_iva_2": "Base tributável a taxa reduzida de IVA",
    "total_reduced_iva_2": "Total do IVA a taxa reduzida",
    "base_taxable_intermediate_iva_2": "Base tributável a taxa intermédia de IVA",
    "total_intermediate_iva_2":  "Total do IVA a taxa intermédia",
    "base_taxable_normal_iva_2": "Base tributável a taxa normal de IVA",
    "total_normal_iva_2": "Total do IVA a taxa normal",
    "fiscal_space_3": "Espaço fiscal 3",
    "base_taxable_exempt_iva_3": "Base tributável isenta de IVA",
    "base_taxable_reduced_iva_3": "Base tributável a taxa reduzida de IVA",
    "total_reduced_iva_3": "Total do IVA a taxa reduzida",
    "base_taxable_intermediate_iva_3": "Base tributável a taxa intermédia de IVA",
    "total_intermediate_iva_3": "Total do IVA a taxa intermédia",
    "base_taxable_normal_iva_3": "Base tributável a taxa normal de IVA",
    "total_normal_iva_3": "Total do IVA a taxa normal",
    "iva_exempt": "Não sujeito a IVA",
    "stamp_tax": "Imposto do selo",
    "total_tax": "Total do impostos",
    "total_gross": "Total do documento com impostos",
    "withholding_tax": "Retenção na fonte",
    "hash": "Hash do documento",
    "certificate_number": "Número do certificado",
    "additional_info": "Informação adicional",
}